### PR TITLE
Clean up some more styles in redesign

### PR DESCRIPTION
**Pull request by dharma-guardian**
I like your redesign and cleaned up some obvious stuff.
screen shot 2016-01-02 at 04 42 59

### CODE REVIEW

**Comment by runn1ng** [comment]
:+1: great! 

I am now just not sure if it would be better to accept this and add this to the existing signal pull request, or wait for whispersystem's response on the original PR first. 

I will *not* maintain this fork if WS think it's not what they want. :)

**Comment by runn1ng** [comment]
The pull request was closed, so who cares really. :) again, I will not maintain this fork long term.

**Comment by dharma-guardian** [comment]
np, I use this style personally right now from my fork. feel free to delete your fork.

**Comment by runn1ng** [comment]
I will keep it, because why not, but I will not merge back the changes from "upstream".

**Pull request merged**
